plugins:
  - jekyll-relative-links
  - jekyll-include-cache # needed by minimal mistakes theme
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

theme: minimal-mistakes-jekyll

title: Dr Kate Storrs
description: New site under construction. For now, go to www.katestorrs.com
